### ISSUE TITLE
ckeditor4 vue with vue2 and bootstrap vue modal

### ISSUE THREAD

**Issue by adrianoGaspar** [ckeditor/ckeditor4-vue#55] opened 2020-09-04 16:46 UTC
Hello, I use ckeditor4 vue with vue2 and bootstrap vue.
The ckeditor4 is inside a modal and the text and numeric fields of the CKEditor4 forms are unfocused, preventing typing.
I know that this is an already known problem and I found some possible solutions but none apply to the case of the VUE. At least I couldn't adapt any of them.
Has anyone ever experienced this? Could you give me some guidance on how to solve it?
Thank you.

**Comment by jacekbogdanski** [comment] 2020-09-07 06:20
> I know that this is an already known problem and I found some possible solutions but none apply to the case of the VUE. At least I couldn't adapt any of them.

@adrianoGaspar could you attach your findings?

Also, could you add some demo sample which would allow us to reproduce the issue?

**Comment by Dumluregn** [comment] 2020-09-21 07:03
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2020-09-21 07:03 UTC
Labels: status:pending
