### ISSUE TITLE
Vue is calling for translation via url? It fails in firefox.

### ISSUE THREAD

**Issue by wiejakp** [ckeditor/ckeditor4-vue#44] opened 2020-07-01 08:49 UTC
Hello, I'm experiencing issue with vue component in Firefox browser only. Please notice the screenshot:

![Screen Shot 2020-07-01 at 3 40 41 AM](https://user-images.githubusercontent.com/22645549/86223704-7ea77100-bb4d-11ea-8c0e-7f85c8f78921.png)

Vue Component:

```
<template>
    <div :data-field="id" class="ck4-text-input">
        <ckeditor v-model="editorData" :config="editorConfig"></ckeditor>
        <textarea :id="id" :name="name" v-model.lazy="editorData" class="d-none"></textarea>

        <div class="slot-wrapper d-none">
            <slot/>
        </div>
    </div>
</template>

<script>
    // normal and legacy release cause the issue
    import CKEditor from 'ckeditor4-vue/dist/legacy';
    import CkShared from './ckShared';

    export default {
        props: {
            id: {type: String, default: 'ck-text-document-${++inc}'},
            name: {type: String},
            config: {type: Object, default: '{}'}
        },
        components: {
            ckeditor: CKEditor.component
        },
        data() {
            return {
                editorUrl: '/ckeditor/ckeditor.js',
                editorData: '',
                customConfig: '',
                defaultLanguage: 'en',
                editorConfig: Object.assign({}, CkShared.config, {
                    allowedContent: {
                        a: {attributes: '!href'},
                        'address b br del i ins p pre sub sup': {},
                        div: {
                            attributes: 'class',
                            classes: 'exception, list, equation_group, equation, equation_content, equation_number, where'
                        },
                        'h1 h2 h3 h4 h5 h6': {},
                        img: {attributes: 'alt, !src, height, width, src-filename'},

                        // lists
                        'ol ul li': {},

                        // tables
                        table: {attributes: 'frame, rules'},
                        'thead tbody tfoot': {attributes: 'align valign'},
                        tr: {},
                        'th td': {
                            attributes: 'colspan, rowspan, align, valign, class',
                            classes: 'left, center, right, justify'
                        },
                    },
                    autoGrow_onStartup: true,
                    bodyClass: '',
                    contentsCss: '/build/ckeditor.css',
                    height: 400,
                    resize_enabled: true,
                    toolbar: CkShared.toolbars.document,
                })
            };
        },
        mounted() {
            this.editorData = this.$el.getElementsByClassName("slot-wrapper")[0].innerHTML;
            this.config = JSON.parse(this.config);

            if (this.editorConfig.removePlugins === undefined) {
                this.editorConfig.removePlugins = '';
            }

            if (typeof this.config.isStaff === 'undefined' || false === this.config.isStaff) {
                let plugins = this.editorConfig.removePlugins.split(',');

                plugins.push('sourcearea');
                plugins.push('elementspath');

                this.editorConfig.removePlugins = plugins.join(',');
            }
        }
    }
</script>
```

Seems like plugins `widgetcontextmenu`, `base64image` are the issue, but i need those working too.

I don't understand why this component is calling translations in the first place. 

Any tips?

**Comment by Dumluregn** [comment] 2020-07-06 09:42
Hello, please note that both [`widgetcontextmenu`](https://ckeditor.com/cke4/addon/widgetcontextmenu) and [`base64image`](https://ckeditor.com/cke4/addon/base64image) are 3rd party plugins - they are not maintained by CKSource, so we can't solve issues caused by them. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution. If you are able to reproduce this issue using one of the official CKEditor 4 builds, please provide us a detailed config and working demo showing the problem.

**Comment by jacekbogdanski** [comment] 2020-07-20 08:41
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2020-07-20 08:41 UTC
Labels: status:pending
