### ISSUE TITLE
Failed to load https://cdn.ckeditor.com/4.17.2/standard-all/ckeditor.js

### ISSUE THREAD

**Issue by taylous** [ckeditor/ckeditor4-vue#157] opened 2023-09-21 03:38 UTC
## Are you reporting a feature request or a bug?

```bash
[ckeditor.js] Error while loading namespace from integrations package Error: Failed to load https://cdn.ckeditor.com/4.17.2/standard-all/ckeditor.js
```
when loading ckeditor, the above error occurs.

i'm currently useing [ckeditor4-vue3](https://github.com/mayasabha/ckeditor4-vue3)
I've been using it well, but yesterday it suddenly started not working.
is it a cdn server problem?

## Other details

* Browser: Chrome latest
* OS: Window 11
* CKEditor version: 4.17.2
* Installed CKEditor plugins: [ckeditor4-vue3](https://github.com/mayasabha/ckeditor4-vue3)

**Comment by jacekbogdanski** [comment] 2023-09-21 08:03
@taylous From what I see, the CDN works correctly (at least accessing from central Europe) and we didn't report any issues. Could you check if it works fine for you right now?

**Comment by taylous** [comment] 2023-09-21 08:47
@jacekbogdanski 
i don't know why, but a TOO_MANY_REDIRECT error occurs when loading ckeditor...
i was using it well, but suddenly it doesn't work.

can I get some **ideas**?

**Comment by jacekbogdanski** [comment] 2023-09-21 10:02
@taylous it's hard to tell, as you are using 3rd party Vue integration ([ckeditor4-vue3](https://github.com/mayasabha/ckeditor4-vue3)) that is not maintainted by CKEditor 4 team. I can recommend getting back to the integration author, as there is a chance something is wrong with the software itself. Another option is to use [the official Vue integration](https://www.npmjs.com/package/ckeditor4-vue).

The CDN works properly, so I'm closing the issue, but if you will find out that the issue is on the CKEditor 4 side, please let us know so we can reopen it.

**Closed by jacekbogdanski** 2023-09-21 10:02 UTC
